import Head from 'next/head'
import { createClient } from 'contentful'
import RecipeCard from '../components/RecipeCard'

export async function getStaticProps() {

  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN
  })

  const res = await client.getEntries({ content_type: 'recipe'})

  return {
    props: {
      recipes: res.items
    },
    //revalidate: 5
  }
}

export default function Home({ recipes }) {
  
  console.log(recipes)

  return (
    <div className="recipe-list">
      <Head>
        <title>Just Add Marmite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {recipes.map((recipe) => (
        <RecipeCard key={recipe.sys.id} recipe={recipe}/>
      ))}

      <style jsx>{`
        .recipe-list {
          display: grid;
          grid-template-columns: 1fr 1fr;
          grid-gap: 20px 60px;
        }
      `}</style>
    </div>
  )
}
